services:
  - type: web
    name: discord-bot-alan
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
    autoDeploy: true
    startCommand: python discord_bot_hosted.py
